name: Build Windows CE Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download cegcc Toolchain
        run: |
          wget https://github.com/brain-hackers/cegcc-build/releases/download/2022-10-26-225811/cegcc-aarch64-2022-10-26-225811.zip
          sudo mkdir -p /opt
          sudo unzip cegcc-aarch64-2022-10-26-225811.zip -d /opt
      - name: Setup Environment
        run: |
          echo 'export PATH="$PATH:/opt/cegcc/bin"' >> ~/.profile
          source ~/.profile
          echo "PATH is now: $PATH"
          which arm-mingw32ce-gcc # arm-mingw32ce-gcc の存在確認
      - name: Build Windows CE Application
        run: make
